### ISSUE TITLE
Pick 3 at a time from stock

### ISSUE THREAD

**Issue by carlbordum** [Akuli/curses-klondike#2]
In another version of klondike, 3 cards are picked from the stock everytime. Then when there are `n`<= 3 cards in the stock and they are picked, the last is shown. The discard pile is then turned upside down (or rather; downside up) and `n` cards are picked the first time.

This is really fun! Thanks for sharing

**Comment by Akuli** [comment]
i'll add a command line option for this next

**Comment by Akuli** [comment]
This is now implemented on master, but it shows all the 3 picked cards instead of the last one. I think this is nicer and less confusing because you can see what happened, and there's no need to try to memorize which cards you have seen lately. What do you think?

if you prefer the old behaviour like I do, pass a `--pick=1` argument (see `--help` for all possible args).

**Comment by carlbordum** [comment]
This is nice. Thanks!

The family rules in my house is to only show the top card of the three (and the elders are very adamant about it!). Making this change would also make the tui work for `--pick 18` :D
Although the current layout is very nice when n is not too large.

**Comment by Akuli** [comment]
I played it with a fullscreen terminal and `--pick 24` yesterday. Maybe I should add a `--show-top-only` option or something.

**Comment by Akuli** [comment]
I started implementing the only show top option, and I ended up with a quesiton that's quite hard to describe in words, but I'll try.

Start a new game. Press s. You see 3 cards in discard. Let's call them card 1, card 2 and card 3 so that card 1 is bottommost and card 3 is topmost. You take card 3 and start moving it somewhere. Now card 2 is "exposed" because it's now the topmost card in discard. Should you be able to see the number and suit of card 2?

**Comment by carlbordum** [comment]
You should not be able to see card 2 before card 3 has been "successfully" placed. And then card 3 (or any other card) can't be moved back.

**Comment by Akuli** [comment]
I need a name for this option. The spaghetti I have now just calls it `Issue2HideMode` or `i2hm` or `i2`, but I think the command line option needs a better name. The `--show-top-only` doesn't feel like it's the best possible, maybe something like `--hide-discard-cards`?

**Comment by Akuli** [comment]
now there's an implementation on a branch named `spaghetti`

**Comment by Akuli** [comment]
It's on master now, the name of the option is `--discard-hide`. Let me know what you think

**Comment by carlbordum** [comment]
This is the game I learned :)

`--show-top-only` is a better name imo.

Still doesn't work for large `--pick`

**Comment by Akuli** [comment]
I don't like `--show-top-only`, because it doesn't say top of *what*. `--show-only-top-of-discard` is way too long and verbose, even though the argument parser supports abbreviations.

Now `--discard-hide` should work better with large `--pick`. Try it and let me know.
